### ISSUE TITLE
Angular JS as optional Dashboard

### ISSUE THREAD

**Issue by tominagaf** [sdtabilit/Scada-LTS#52]
Mango M2M has an insteresting feature called Custom Dashboards which is based on Angular JS interface. You can see it here https://vimeo.com/179788325 

It would be really nice having this dashboard.

It would help too:
https://github.com/infiniteautomation/mango-ng-ui

**Comment by grzesiekb** [comment]
Welcome!
We have a task management hosted on JIRA cloud (https://scadalts.atlassian.net). Please provide us email to send you invitation. Are you going to participate or contribute into this feature?

**Comment by tominagaf** [comment]
Hello, 
We have been talking by email. I am just an advanced user, but I can contribute on testing and whatever you need. I am teaching myself coding but I am a begginer. 

Please send the invitation to this email: webmonitor@outlook.com
